repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: debug-statements
#      - id: end-of-file-fixer  # doesn't interact well with nbqa
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: fd5ba70665a37ec301a1f714ed09336048b3be63  # frozen: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: 486760aeedfeed700b8fa8b359ba91f77d540ec4  # frozen: v2.26.0
    hooks:
      - id: pyupgrade
        args: [ "--py37-plus" ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: e7fbd791e6ca56213997f47a22c5655ed375deb5  # frozen: 1.1.1
    hooks:
      - id: nbqa-pyupgrade
        additional_dependencies: [ pyupgrade==2.19.4 ]
        args: [ "--py37-plus" ]
      - id: nbqa-isort
        additional_dependencies: [ isort==5.9.1 ]
        args: [ "--nbqa-mutate" ]

  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: 551ab39ffcb92404c78593515520b05ec1dab9e3  # frozen: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
#        args:
#           - --remove-kernel-metadata
#          - --pin-patterns
#          - "[pin];[donotremove]"
